export const FRIEND_REPOSITORY = Symbol('IFriendRepository');

export const FRIEND_ERROR_CODES = {
  FRIEND_NOT_FOUND: 'FRIEND_NOT_FOUND',
  FRIEND_ALREADY_ARCHIVED: 'FRIEND_ALREADY_ARCHIVED',
  FRIEND_NOT_ARCHIVED: 'FRIEND_NOT_ARCHIVED',
} as const;
