export const MATCH_REPOSITORY = Symbol('IMatchRepository');

export const MATCH_ERROR_CODES = {
  MATCH_NOT_FOUND: 'MATCH_NOT_FOUND',
  CONFIRMED_MATCH_UNDELETABLE: 'CONFIRMED_MATCH_UNDELETABLE',
  INVALID_MATCH_STATE: 'INVALID_MATCH_STATE',
} as const;
